### ISSUE TITLE
Update dependencies' versions

### ISSUE THREAD

**Issue by villekr** [villekr/ocpp-asgi#12]
```
[tool.poetry.dependencies]
python = "^3.8"
ocpp = "^0.8.3"

[tool.poetry.dev-dependencies]
websockets = "9.1"
aiohttp = "3.7.4"
uvicorn = "0.14.0"
black = "21.7b0"
flake8 = "3.9.2"
isort = "5.9.2"
pytest = "6.2.4"
pytest-cov = "2.12.1"
pytest-asyncio = "0.15.1"
asgi-tools = "0.61.6"
```

**Comment by ChaitanyaYeole02** [comment]
Can we have Python 3.10, as in 3.8 we get asyncio future exception when it tries to create another task and send it to the client also, In websockets 10.3 we can get timeout features which I think will be very helpful.
I wanted to ask if there is any reason for ocpp to be 0.8.3 or we can upgrade that too, as there are few libraries and enums changes in the latest version.
Thank you @villekr

**Comment by ChaitanyaYeole02** [comment]
Yes, and can we have releases for ocpp-asgi library currently 0.2.0 is going as new bugs are found and fixes happen, you can upgrade the release version as well?

**Comment by villekr** [comment]
Updated dependency list.

```
[tool.poetry.dependencies]
python = "^3.8"
ocpp = "^0.15.0"

[tool.poetry.dev-dependencies]
websockets = "10.3"
aiohttp = "3.8.3"
uvicorn = "0.18.3"
black = "22.8.0"
flake8 = "5.0.4"
isort = "5.10.1"
pytest = "7.1.3"
pytest-cov = "3.0.0"
pytest-asyncio = "0.19.0"
asgi-tools = "0.64.1"
```

**Comment by villekr** [comment]
You can use ocpp-asgi with Python 3.10 fine. Will keep python ^3.8 dependency requirement unchanged.
