### ISSUE TITLE
Half TCP connection closed error

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [villekr/ocpp-asgi#8]
I received this error when I disconnected my charger while a message was still in process. 
@villekr This could be changed in the next version.
```
    async def on_receive(self, *, message: str, context: RouterContext):
        router: Router = self.routers[context.subprotocol]
        try:
            await router.route_message(message=message, context=context)
        except:
            pass
```

**Comment by villekr** [comment]
This should be handled correctly in fix https://github.com/villekr/ocpp-asgi/pull/11.
